export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const EDITING_PRODUCT = "EDITING_PRODUCT";
